# Custom Language File for Launcher Customizer

[ejs.app]
title = "SworldCraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/7RJrhEGz78"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO SWORLDCRAFT"
welcomeDescription = "Serveur Minecraft moddé axé sur le build, la conquête de territoires et l’économie. Construis des villes et des bases durables, revendique et défends tes zones, puis développe ta puissance grâce à un système économique (commerce, métiers, échanges entre joueurs). Joue en solo ou en faction, forme des alliances et impose ton influence sur le monde."
welcomeDescCTA = "You are just a few clicks away from Westeros."
